### ISSUE TITLE
`ctc ens` bug

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/checkthechain#10]
OS: WSL/Ubuntu 20.04
Python 3.8.10
RPC: HTTP Alchemy API

```
(base) caleb@CORUSCANT:~/fei-protocol-core$ ctc ens kryptoklob.eth
fetching abi from etherscan: 0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85
saving contract_abi to: /home/caleb/.ctcdata/mainnet/contract_abis/contract__0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/contract__0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85.json
┌────────────────┐
│ kryptoklob.eth │
└────────────────┘
- address: 0x11e52c75998fe2e7928b191bfc5b25937ca16741
- owner: 0x11e52c75998fe2e7928b191bfc5b25937ca16741
- resolver: 0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41
- namehash: 0xe5e3e30326d8180ff080e07c5a926d021ffc236d5a94da8471e5993fb5da023e
- expiration: 2025-05-04 05:06:00Z
fetching abi from etherscan: 0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41
sleeping 5.284180641174316 seconds for etherscan ratelimit
/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/contract_abi_backends/etherscan_contract_abis.py:35: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(sleep_time)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/__main__.py", line 4, in <module>
    ctc.cli.run_cli()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/cli/cli_run.py", line 163, in run_cli
    toolcli.run_cli(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 55, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 74, in execute_parsed_command
    execute_command_spec(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 122, in execute_command_spec
    asyncio.run(function(**args))
  File "/home/caleb/miniconda3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/caleb/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/protocols/ens_utils/cli/ens_command.py", line 54, in ens_command
    text_records = await ens_utils.async_get_text_records(name=name)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/protocols/ens_utils/resolver.py", line 99, in async_get_text_records
    text_changes = await async_get_text_changes(name=name, node=node)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/protocols/ens_utils/resolver.py", line 109, in async_get_text_changes
    events = await evm.async_get_events(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/event_utils/event_crud.py", line 58, in async_get_events
    events = await backend_utils.async_run_on_backend(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/backend_utils/backend_crud.py", line 37, in async_run_on_backend
    return await function(**function_kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/event_utils/event_backends/filesystem_events.py", line 359, in async_get_events_from_filesystem
    event_abi = await abi_utils.async_get_event_abi(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/event_abi_io.py", line 19, in async_get_event_abi
    contract_abi = await contract_abi_io.async_get_contract_abi(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/contract_abi_io.py", line 31, in async_get_contract_abi
    return await backend_utils.async_run_on_backend(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/backend_utils/backend_crud.py", line 37, in async_run_on_backend
    return await function(**function_kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/contract_abi_io.py", line 71, in async_download_contract_abi
    contract_abi = await async_transfer_contract_abi(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/contract_abi_io.py", line 44, in async_transfer_contract_abi
    return await backend_utils.async_transfer_backends(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/backend_utils/backend_crud.py", line 87, in async_transfer_backends
    result = await get(backend=from_backend, **get_kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/contract_abi_io.py", line 31, in async_get_contract_abi
    return await backend_utils.async_run_on_backend(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/backend_utils/backend_crud.py", line 37, in async_run_on_backend
    return await function(**function_kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/abi_utils/abi_io/contract_abi_backends/etherscan_contract_abis.py", line 49, in async_get_contract_abi_from_etherscan
    raise Exception(
Exception: could not obtain contract abi from etherscan for 0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1ab3f72e80>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1ab33c2dc0>, 18561.8661614)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1ab3f72eb0>
```

**Comment by sslivkoff** [comment]
fixed in cceaa5865b1261397e0797bf27cc874b5a365c71
