### ISSUE TITLE
`ctc erc20 balances xxxx` issue

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/checkthechain#13]
OS: Win11 + WSL/Ubuntu 20.04

Just upgraded to the latest version.

```
(base) caleb@CORUSCANT:/$ ctc erc20 balances 0x11e52c75998fe2E7928B191bfc5B25937Ca16741
searching for creation block of 0x11e52c75998fe2E7928B191bfc5B25937Ca16741
- trying block: 0
- trying block: 14537156
Traceback (most recent call last):
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/__main__.py", line 4, in <module>
    ctc.cli.run_cli()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/cli/cli_run.py", line 163, in run_cli
    toolcli.run_cli(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 55, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 74, in execute_parsed_command
    execute_command_spec(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 122, in execute_command_spec
    asyncio.run(function(**args))
  File "/home/caleb/miniconda3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/caleb/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/cli/commands/data/erc20/balances_command.py", line 151, in async_balances_command
    transfers = await evm.async_get_erc20_transfers(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/erc20_utils/erc20_events.py", line 30, in async_get_erc20_transfers
    transfers = await event_utils.async_get_events(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/event_utils/event_crud.py", line 45, in async_get_events
    start_block = await block_utils.async_get_contract_creation_block(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/evm/block_utils/block_search.py", line 62, in async_get_contract_creation_block
    result = await search_utils.async_binary_search(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/search_utils.py", line 124, in async_binary_search
    raise NoMatchFound('could not find match')
ctc.toolbox.search_utils.NoMatchFound: could not find match
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1b8e6b7c10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1b8c42cee0>, 1622.7398384)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1b8ea3f250>
sys:1: RuntimeWarning: coroutine 'async_get_erc20_symbol' was never awaited
```

**Comment by ditchfieldcaleb** [comment]
Oh, I guess this is meant to be used on a contract only? I thought the helper text meant that you could track one addresses' erc20 balances - all of them.

**Comment by sslivkoff** [comment]
this can be used to get multiple erc20 balances of a single wallet, but you have to specify which erc20s

added clarifying error message in 4ea8f38f
