### ISSUE TITLE
`ctc config file does not exist` even after running `ctc setup`

### ISSUE THREAD

**Issue by sjkelleyjr** [fei-protocol/checkthechain#45]
I've run `ctc setup` with all defaults, once after initial install, and once again when I saw the above warning.  However, the warning doesn't seem to go away.

I thought maybe it was an errant warning, so I tried tracing a tx hash and got this

```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<async_eth_get_transaction_receipt() done, defined at /Library/Python/3.8/site-packages/ctc/rpc/rpc_executors/rpc_transaction_executors.py:90> exception=ConfigInvalid("provider should have keys: {'convert_reverts_to_none', 'session_kwargs', 'network', 'chunk_size', 'name', 'url', 'protocol'}")>
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/ctc/rpc/rpc_executors/rpc_transaction_executors.py", line 100, in async_eth_get_transaction_receipt
    response = await rpc_request.async_send(request, provider=provider)
  File "/Library/Python/3.8/site-packages/ctc/rpc/rpc_request.py", line 102, in async_send
    full_provider = rpc_provider.get_provider(provider)
  File "/Library/Python/3.8/site-packages/ctc/rpc/rpc_provider.py", line 15, in get_provider
    return ctc.config.get_default_provider()
  File "/Library/Python/3.8/site-packages/ctc/config/config_values.py", line 143, in get_default_provider
    network = get_default_network()
  File "/Library/Python/3.8/site-packages/ctc/config/config_values.py", line 44, in get_default_network
    return config_read.get_config().get('default_network')
  File "/Library/Python/3.8/site-packages/ctc/config/config_read.py", line 111, in get_config
    config_validate.validate_config(config)
  File "/Library/Python/3.8/site-packages/ctc/config/config_validate.py", line 68, in validate_config
    key_validator(value=value, config=config)
  File "/Library/Python/3.8/site-packages/ctc/config/config_validate.py", line 142, in validate_providers
    raise spec.ConfigInvalid(
ctc.spec.exceptions.config_exceptions.ConfigInvalid: provider should have keys: {'convert_reverts_to_none', 'session_kwargs', 'network', 'chunk_size', 'name', 'url', 'protocol'
```

**Comment by sslivkoff** [comment]
is a `config.json` file generated in the `~/.config/ctc` dir? if so can you post the config here (with provider url removed)?

**Comment by sjkelleyjr** [comment]
nope

**Comment by detroitcoder** [comment]
Did you specify a custom ctc_data location? If so, try using the default. I saw a similar error at the end of ctc setup in one of my variations of debugging an issue.

**Comment by sjkelleyjr** [comment]
I ran `ctc setup` with all defaults.

The only question I see related to data location is 

```
## Data Root Directory

Continue using data directory /Users/jackson/ctc_data?
(default = yes)
```

to which I'm selecting the default.  I don't see a question about the `ctc_data` location.  Is this set somewhere in a file that I can check?

**Comment by sjkelleyjr** [comment]
In the short term, is there a default config file I can just copy/paste to the `~/.config/ctc` directory?

**Comment by sslivkoff** [comment]
pasting a config file won't work on it's own because the setup process needs to initiate the filesystem. 

it's complaining that the rpc provider is ill formatted. can you run `ctc setup --debug`, and then in this issue paste the output of `print(provider)` (omit your private provider url)

also, from the path format it looks like youre using a mac. is this correct?

**Comment by sjkelleyjr** [comment]
>also, from the path format it looks like youre using a mac. is this correct?

yep

Here's the output from `print(provider)`, with my API key substituted out.
```
{'name': 'ETH_RPC_URL', 'network': 1, 'protocol': 'http', 'url': 'https://eth-mainnet.alchemyapi.io/v2/MY_API_KEY', 'session_kwargs': {}, 'chunk_size': None}
```

**Comment by jameswenzel** [comment]
I am running into this same error, also on macOS - I've tried with both Alchemy and Infura provider URLs.

Here is the output of `print(provider)` in PDB for me:

```
{'name': 'ETH_RPC_URL', 'network': 1, 'protocol': 'http', 'url': 'https://mainnet.infura.io/v3/MY_API_KEY', 'session_kwargs': {}, 'chunk_size': None}
```

**Comment by trangnv** [comment]
I also use macOS, ran into the same problem when I change the recommended `data_dir`. It worked fine when I let it as default value

**Comment by Poor4ever** [comment]
same problem,if environment variable has  `ETH_RPC_URL`,`ctc setup` doesn't work,

temporary methods to make it work properly:
delete the `ETH_RPC_URL` environment variable or add `'convert_reverts_to_none': False` in the `add_env_var_rpc_provider` function of `config_defaults.py` under `default_config['providers'][provider_name]`.

**Comment by sjkelleyjr** [comment]
I haven't tried it yet, but I'm about 99% sure this was my problem since I have that same environment variable.  Ty!
