### ISSUE TITLE
more than one match found in sequence, FIXED, TODO: add more tests

### ISSUE THREAD

**Issue by brent14** [fei-protocol/checkthechain#47]
I am not able to retrieve a contract abi or call all on a contract.  I have tried multiple contracts and they all seem to return the same error of "more than one match found in sequence".  Below is an example using the Dai Contract.

I'm running python version 3.9.12 on mac osx 12.5.1.

```
ctc abi 0x6B175474E89094C44Da98b954EedeAC495271d0F
fetching mainnet abi from etherscan: 0x6B175474E89094C44Da98b954EedeAC495271d0F
more than one match found in sequence

ctc call all 0x6B175474E89094C44Da98b954EedeAC495271d0F
fetching mainnet abi from etherscan: 0x6B175474E89094C44Da98b954EedeAC495271d0F
more than one match found in sequence
```

**Comment by detroitcoder** [comment]
For what it works this does work for me. Are you using eth mainnet as your default network?

![image](https://user-images.githubusercontent.com/6266683/193721635-8ecdcc07-ba63-4951-b7b5-608ff204e1e3.png)

**Comment by sslivkoff** [comment]
@brent14 can you run `ctc abi 0x6B175474E89094C44Da98b954EedeAC495271d0F --debug` and post the stack trace

**Comment by brent14** [comment]
This is the output i get from running that command.

@detroitcoder I believe the request is using mainnet.

```
ctc abi 0x6B175474E89094C44Da98b954EedeAC495271d0F --debug
fetching mainnet abi from etherscan: 0x6B175474E89094C44Da98b954EedeAC495271d0F
[ENTERING DEBUGGER]
Traceback (most recent call last):
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/toolcli/command_utils/execution.py", line 56, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/toolcli/command_utils/execution.py", line 84, in execute_parsed_command
    execute_command_spec(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/toolcli/command_utils/execution.py", line 130, in execute_command_spec
    asyncio.run(coroutine)
  File "/Users/brent/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/brent/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/toolcli/command_utils/execution.py", line 143, in _async_execute_in_context_manager
    await function(**args)
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/cli/commands/data/abi_command.py", line 117, in async_abi_command
    contract_abi = await evm.async_get_contract_abi(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/evm/abi_utils/contract_abi_utils/contract_abi_io.py", line 60, in async_get_contract_abi
    await address_utils.async_get_proxy_implementation(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/evm/address_utils/proxy_utils.py", line 33, in async_get_proxy_implementation
    proxy_metadata = await async_get_proxy_metadata(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/evm/address_utils/proxy_utils.py", line 64, in async_get_proxy_metadata
    eip1967_logic_address = await _async_get_eip1967_proxy_logic_address(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/evm/address_utils/proxy_utils.py", line 205, in _async_get_eip1967_proxy_logic_address
    result = await rpc.async_eth_get_storage_at(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/rpc/rpc_executors/rpc_state_executors.py", line 163, in async_eth_get_storage_at
    response = await rpc_request.async_send(request, provider=provider)
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/rpc/rpc_request.py", line 102, in async_send
    full_provider = rpc_provider.get_provider(provider)
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/rpc/rpc_provider.py", line 59, in get_provider
    base_provider = ctc.config.get_provider(
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/config/config_values.py", line 133, in get_provider
    return search_utils.get_matching_entry(sequence=providers, query=query)
  File "/Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/toolbox/search_utils.py", line 66, in get_matching_entry
    raise MultipleMatchesFound('more than one match found in sequence')
ctc.toolbox.search_utils.MultipleMatchesFound: more than one match found in sequence

> /Users/brent/opt/anaconda3/lib/python3.9/site-packages/ctc/toolbox/search_utils.py(66)get_matching_entry()
-> raise MultipleMatchesFound('more than one match found in sequence')
```

**Comment by sslivkoff** [comment]
ok from that it looks like you're using multiple providers for a single network, and it looks like there's a bug with handling that. patched here [a04e148](https://github.com/fei-protocol/checkthechain/commit/a04e14893545fc6ae7e7845c4ca2f4f0f0906ab0).

I will add more tests for multi-provider-single-network setups and will push a new release to pypi by end of week

just to confirm, can you post the `providers` section printed when you run the `ctc config` command?

**Comment by brent14** [comment]
I did setup two providers so that makes sense.  I'll try the patch and let you know that it works.

```

- providers:
            name  │  network  │       url
    ──────────────┼───────────┼────────────
      alchemy__1  │  mainnet  │  ********
       infura__1  │  mainnet  │  ********

```

**Comment by brent14** [comment]
@sslivkoff it works now with that update.

Thanks.
