### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by XingyuLi20** [fei-protocol/checkthechain#48]
After running `ctc setup` to config my RPC url, and then running `llama pools`, I got the following error:

```
ConnectionKey(host='yields.llama.fi', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)
```

The RPC URL is valid and works fine on other projects. Wonder what's the causes of it and it would be great to have better error message display. Thanks!

**Comment by detroitcoder** [comment]
This is likely not related to the RPC URL setup because this data is pulled directly from the defi llama API directly. It looks like this error is an http request error. Are you able to access the below URL from your network in a browser? You should get json back that says` {"message": "Not Found"}
`
https://yields.llama.fi/

-Michael

**Comment by sslivkoff** [comment]
are you using an M1 mac? Ive been receiving multiple reports of networking errors in M1 environments

if not, can you provide your os version + python version

**Comment by XingyuLi20** [comment]
Yes, I am using M1 Pro. 
- OS Version: macOS Monterey 12.3
- Python Version: Python 3.10.6

**Comment by sslivkoff** [comment]
not sure why, but networking seems to break on apple m1's

I don't have access to an M1 right now so unfortunately cannot debug this very well

**Comment by kasperpawlowski** [comment]
@XingyuLi20 Navigate to your `Applications/Python 3.x/` folder and double click the `Install Certificates.command`

More on this in `Applications/Python 3.x/ReadMe.rtf`

**Comment by sslivkoff** [comment]
@kasperpawlowski is it a cert issue? that would explain a lot

**Comment by sslivkoff** [comment]
@kasperpawlowski and did running `/Applications/Python 3.x/Install Certificates.command` seem to totally resolve the issue?

if so then ctc can check for this in a straightforward way and give M1 users a helpful error message about how to resolve

**Comment by sslivkoff** [comment]
@kasperpawlowski thanks for the insights. I will dig into this more when I get a chance

**Comment by XingyuLi20** [comment]
Hey @kasperpawlowski thanks for the response. However, I'm having trouble finding `/Applications/Python 3.x/Install Certificates.command` on my laptop. I was able to navigate to the `site-packages` folder but don't see any relevant commands. Any instructions for this? Appreciate it!

**Comment by sslivkoff** [comment]
@XingyuLi20 can you post the full stack trace that of the error that you get during setup?

**Comment by XingyuLi20** [comment]
Command: `llama pools --debug`
Full Stack Trace:
```
[ENTERING DEBUGGER]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 56, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 84, in execute_parsed_command
    execute_command_spec(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 130, in execute_command_spec
    asyncio.run(coroutine)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 143, in _async_execute_in_context_manager
    await function(**args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ctc/protocols/llama_utils/cli/llama_pools_command.py", line 121, in async_llama_pools_command
    await llama_yields.async_print_llama_pools_summary(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ctc/protocols/llama_utils/llama_yields.py", line 36, in async_print_llama_pools_summary
    pools = await llama_requests.async_get_llama_pools(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ctc/protocols/llama_utils/llama_requests.py", line 135, in async_get_llama_pools
    data = await async_request_llama_data('pools')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ctc/protocols/llama_utils/llama_requests.py", line 53, in async_request_llama_data
    async with session.get(url) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host yields.llama.fi:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

> /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py(988)_wrap_create_connection()
-> raise ClientConnectorCertificateError(req.connection_key, exc) from exc
(Pdb)
```

**Comment by kasperpawlowski** [comment]
@XingyuLi20 it might be worth reinstalling python on your machine using the official installer. it seems that you're facing the same issue, but I have no idea where you can find the relevant `Install Certificates.command` under your setup

https://www.python.org/downloads/
