### ISSUE TITLE
ctc setup fails with non-default data root directory

### ISSUE THREAD

**Issue by MantisClone** [fei-protocol/checkthechain#51]
```console
(venv) david@david-Inspiron-5502:~/projects/ctc-playground$ ctc setup --debug
# Setting up ctc...

Running setup process for ctc 0.3.0

Each step is optional
- by default, setup process will leave existing settings unchanged
- setup can be rerun multiple times idempotently

Can skip options by pressing enter at each prompt
old_config has unknown version, using default config


## Network Setup


Most ctc operations require an RPC provider

Would you like to specify an RPC provider? (default = yes) 

What is the RPC provider URL? https://polygon-mainnet.g.alchemy.com/v2/<ALCHEMY_API_KEY>
Provider using: chain_id = 137, network = polygon
What should this node be called? (default = alchemy__137) 
Would you like to specify additional RPC providers? (default = no) 

Have metadata for the following networks:

      │              name  │       chain_id  
──────┼────────────────────┼─────────────────
   1  │           mainnet  │              1  
   2  │           ropsten  │              3  
   3  │           rinkeby  │              4  
   4  │            goerli  │              5  
   5  │          optimism  │             10  
   6  │             kovan  │             42  
   7  │               bnb  │             56  
   8  │    optimism_kovan  │             69  
   9  │       bnb_testnet  │             97  
  10  │            gnosis  │            100  
  11  │              heco  │            128  
  12  │           polygon  │            137  
  13  │            fantom  │            250  
  14  │   optimism_goerli  │            420  
  15  │             metis  │          1,088  
  16  │          moonbeam  │          1,284  
  17  │         moonriver  │          1,285  
  18  │    fantom_testnet  │          4,002  
  19  │            klaytn  │          8,217  
  20  │          arbitrum  │         42,161  
  21  │    avalanche_fuji  │         43,113  
  22  │         avalanche  │         43,114  
  23  │    polygon_mumbai  │         80,001  
  24  │  arbitrum_rinkeby  │        421,611  
  25  │           harmony  │  1,666,600,000  
  26  │   harmony_testnet  │  1,666,700,000  

Would you like to add metadata for additional networks? (default = no) 

Using 26 networks in config

Which network to use as default?
    1. arbitrum (chain_id = 42161)
    2. arbitrum_rinkeby (chain_id = 421611)
    3. avalanche (chain_id = 43114)
    4. avalanche_fuji (chain_id = 43113)
    5. bnb (chain_id = 56)
    6. bnb_testnet (chain_id = 97)
    7. fantom (chain_id = 250)
    8. fantom_testnet (chain_id = 4002)
    9. gnosis (chain_id = 100)
    10. goerli (chain_id = 5)
    11. harmony (chain_id = 1666600000)
    12. harmony_testnet (chain_id = 1666700000)
    13. heco (chain_id = 128)
    14. klaytn (chain_id = 8217)
    15. kovan (chain_id = 42)
    16. mainnet (chain_id = 1)
    17. metis (chain_id = 1088)
    18. moonbeam (chain_id = 1284)
    19. moonriver (chain_id = 1285)
    20. optimism (chain_id = 10)
    21. optimism_goerli (chain_id = 420)
    22. optimism_kovan (chain_id = 69)
    23. polygon (chain_id = 137) (default)
    24. polygon_mumbai (chain_id = 80001)
    25. rinkeby (chain_id = 4)
    26. ropsten (chain_id = 3)
(default = polygon (chain_id = 137))

(default = polygon (chain_id = 137))
> 

Network setup complete


## Data Root Directory

Where should ctc store data? (specify a directory path) (default = /home/david/ctc_data) /home/david/projects/ctc-playground
creating directory: /home/david/projects/ctc-playground/dbs
creating directory: /home/david/projects/ctc-playground/logs
creating directory: /home/david/projects/ctc-playground/evm
creating directory: /home/david/projects/ctc-playground/logs/rpc
creating directory: /home/david/projects/ctc-playground/logs/db

Do you want to disable ctc logging? (default = no) 


## Database Setup

ctc stores its collected chain data in an sql database

Creating database at path /home/david/projects/ctc-playground/dbs/ctc.db

[WARNING] ctc config file does not exist; use `ctc setup` on command line to generate a config file
[ENTERING DEBUGGER]
Traceback (most recent call last):
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 320, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
    rec = pool._do_get()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
    return _ConnectionRecord(self)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
    self.__connect()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 677, in __connect
    with util.safe_reraise():
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 56, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 84, in execute_parsed_command
    execute_command_spec(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 130, in execute_command_spec
    asyncio.run(coroutine)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 143, in _async_execute_in_context_manager
    await function(**args)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/cli/commands/admin/setup_command.py", line 96, in async_setup_command
    await setup_utils.async_setup_ctc(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/config/setup_utils/main_setup.py", line 80, in async_setup_ctc
    db_data = db_setup.setup_dbs(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/config/setup_utils/stages/db_setup.py", line 61, in setup_dbs
    _delete_incomplete_chainlink_schemas()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/config/setup_utils/stages/db_setup.py", line 130, in _delete_incomplete_chainlink_schemas
    metadata = toolsql.create_metadata_object_from_db(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/sqlalchemy_utils/metadata_utils.py", line 41, in create_metadata_object_from_db
    return _create_metadata_object_from_engine(engine=engine)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcache/cache_decorator.py", line 136, in new_f
    return execute_with_cache(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcache/cache_decorator.py", line 236, in execute_with_cache
    output = old_f(*args, **kwargs)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/sqlalchemy_utils/metadata_utils.py", line 62, in _create_metadata_object_from_engine
    metadata.reflect(bind=engine)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4829, in reflect
    with inspection.inspect(bind)._inspection_context() as insp:
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
    init(self, bind)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
    engine.connect().close()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 320, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
    rec = pool._do_get()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
    return _ConnectionRecord(self)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
    self.__connect()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 677, in __connect
    with util.safe_reraise():
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

> /home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py(598)connect()
-> return self.dbapi.connect(*cargs, **cparams)
(Pdb) c
```

**Comment by detroitcoder** [comment]
Same issue as https://github.com/fei-protocol/checkthechain/issues/50. This was resolved with this [commit](https://github.com/fei-protocol/checkthechain/commit/900f71e97f1628c8631c33fb30cb4da9c227f0f4)
