### ISSUE TITLE
ctc setup fails on Polygon, `table not found in db: network_1__erc20_metadata` 

### ISSUE THREAD

**Issue by MantisClone** [fei-protocol/checkthechain#52]
```console
(venv) david@david-Inspiron-5502:~/projects/ctc-playground$ ctc setup --debug
# Setting up ctc...

Running setup process for ctc 0.3.0

Each step is optional
- by default, setup process will leave existing settings unchanged
- setup can be rerun multiple times idempotently

Can skip options by pressing enter at each prompt
old_config has unknown version, using default config


## Network Setup


Most ctc operations require an RPC provider

Would you like to specify an RPC provider? (default = yes) 

What is the RPC provider URL? https://polygon-mainnet.g.alchemy.com/v2/<ALCHEMY_API_KEY>
Provider using: chain_id = 137, network = polygon
What should this node be called? (default = alchemy__137) 
Would you like to specify additional RPC providers? (default = no) 

Have metadata for the following networks:

      │              name  │       chain_id  
──────┼────────────────────┼─────────────────
   1  │           mainnet  │              1  
   2  │           ropsten  │              3  
   3  │           rinkeby  │              4  
   4  │            goerli  │              5  
   5  │          optimism  │             10  
   6  │             kovan  │             42  
   7  │               bnb  │             56  
   8  │    optimism_kovan  │             69  
   9  │       bnb_testnet  │             97  
  10  │            gnosis  │            100  
  11  │              heco  │            128  
  12  │           polygon  │            137  
  13  │            fantom  │            250  
  14  │   optimism_goerli  │            420  
  15  │             metis  │          1,088  
  16  │          moonbeam  │          1,284  
  17  │         moonriver  │          1,285  
  18  │    fantom_testnet  │          4,002  
  19  │            klaytn  │          8,217  
  20  │          arbitrum  │         42,161  
  21  │    avalanche_fuji  │         43,113  
  22  │         avalanche  │         43,114  
  23  │    polygon_mumbai  │         80,001  
  24  │  arbitrum_rinkeby  │        421,611  
  25  │           harmony  │  1,666,600,000  
  26  │   harmony_testnet  │  1,666,700,000  

Would you like to add metadata for additional networks? (default = no) 

Using 26 networks in config

Which network to use as default?
    1. arbitrum (chain_id = 42161)
    2. arbitrum_rinkeby (chain_id = 421611)
    3. avalanche (chain_id = 43114)
    4. avalanche_fuji (chain_id = 43113)
    5. bnb (chain_id = 56)
    6. bnb_testnet (chain_id = 97)
    7. fantom (chain_id = 250)
    8. fantom_testnet (chain_id = 4002)
    9. gnosis (chain_id = 100)
    10. goerli (chain_id = 5)
    11. harmony (chain_id = 1666600000)
    12. harmony_testnet (chain_id = 1666700000)
    13. heco (chain_id = 128)
    14. klaytn (chain_id = 8217)
    15. kovan (chain_id = 42)
    16. mainnet (chain_id = 1)
    17. metis (chain_id = 1088)
    18. moonbeam (chain_id = 1284)
    19. moonriver (chain_id = 1285)
    20. optimism (chain_id = 10)
    21. optimism_goerli (chain_id = 420)
    22. optimism_kovan (chain_id = 69)
    23. polygon (chain_id = 137) (default)
    24. polygon_mumbai (chain_id = 80001)
    25. rinkeby (chain_id = 4)
    26. ropsten (chain_id = 3)
(default = polygon (chain_id = 137))

(default = polygon (chain_id = 137))
> 

Network setup complete


## Data Root Directory

Where should ctc store data? (specify a directory path) (default = /home/david/ctc_data) 
creating directory: /home/david/ctc_data/dbs
creating directory: /home/david/ctc_data/logs
creating directory: /home/david/ctc_data/evm
creating directory: /home/david/ctc_data/logs/rpc
creating directory: /home/david/ctc_data/logs/db

Do you want to disable ctc logging? (default = no) 


## Database Setup

ctc stores its collected chain data in an sql database

Creating database at path /home/david/ctc_data/dbs/ctc.db

[WARNING] ctc config file does not exist; use `ctc setup` on command line to generate a config file

Actively using 10 schema(s) across 1 network(s)
    - schemas:
        - block_timestamps
        - block_gas
        - blocks
        - contract_abis
        - contract_creation_blocks
        - erc20_metadata
        - dex_pools
        - chainlink
        - 4byte
        - coingecko
    - network: 137

Schemas to create:
- block_timestamps [network = 137]
- block_gas [network = 137]
- blocks [network = 137]
- contract_abis [network = 137]
- contract_creation_blocks [network = 137]
- erc20_metadata [network = 137]
- dex_pools [network = 137]
- chainlink [network = 137]
- 4byte [network = None]
- coingecko [network = None]

All tables created


## Creating Configuration File

Config file created at /home/david/.config/ctc/config.json


## Populating Database

Populating database with metadata of common ERC20 tokens...

[ENTERING DEBUGGER]
Traceback (most recent call last):
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 56, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 84, in execute_parsed_command
    execute_command_spec(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 130, in execute_command_spec
    asyncio.run(coroutine)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolcli/command_utils/execution.py", line 143, in _async_execute_in_context_manager
    await function(**args)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/cli/commands/admin/setup_command.py", line 96, in async_setup_command
    await setup_utils.async_setup_ctc(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/config/setup_utils/main_setup.py", line 106, in async_setup_ctc
    await db_setup.async_populate_db_tables(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/config/setup_utils/stages/db_setup.py", line 102, in async_populate_db_tables
    await default_erc20s.async_intake_default_erc20s(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/config/setup_utils/default_data/default_erc20s.py", line 37, in async_intake_default_erc20s
    await db.async_upsert_erc20s_metadata(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/db/schemas/erc20_metadata/erc20_metadata_statements.py", line 61, in async_upsert_erc20s_metadata
    await asyncio.gather(*coroutines)
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/ctc/db/schemas/erc20_metadata/erc20_metadata_statements.py", line 43, in async_upsert_erc20_metadata
    toolsql.insert(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/crud_utils/create.py", line 28, in insert
    return insert_row(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/crud_utils/create.py", line 55, in insert_row
    statement = create_insert_statement(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/crud_utils/create.py", line 184, in create_insert_statement
    table = sqlalchemy_utils.create_table_object_from_db(
  File "/home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/sqlalchemy_utils/table_utils.py", line 122, in create_table_object_from_db
    raise exceptions.TableNotFound(
toolsql.exceptions.TableNotFound: table not found in db: network_1__erc20_metadata

> /home/david/projects/ctc-playground/venv/lib/python3.10/site-packages/toolsql/sqlalchemy_utils/table_utils.py(122)create_table_object_from_db()
-> raise exceptions.TableNotFound(
(Pdb) c
```

**Comment by ArtBreguez** [comment]
same here, got it fixed?
