### ISSUE TITLE
KeyError 'id' in chunk 

### ISSUE THREAD

**Issue by josecyc** [fei-protocol/checkthechain#79]
I randomly get a KeyError while getting the transaction receipt with this: `response = await rpc.async_batch_eth_get_transaction_receipt(transaction_hashes=chunk)`

Here's the trace

```
Traceback (most recent call last):
  ... line 2087, in parse_block_for_events
    response = await rpc.async_batch_eth_get_transaction_receipt(transaction_hashes=chunk)
  File ".../lib/python3.10/site-packages/ctc/rpc/rpc_batch/rpc_batch_executors.py", line 227, in async_batch_eth_get_transaction_receipt
    return await rpc_batch_utils.async_batch_execute(
  File ".../lib/python3.10/site-packages/ctc/rpc/rpc_batch/rpc_batch_utils.py", line 93, in async_batch_execute
    response = await rpc_request.async_send(
  File ".../lib/python3.10/site-packages/ctc/rpc/rpc_request/request_async.py", line 127, in async_send
    output = request_utils._postprocess_plural_response(
  File ".../lib/python3.10/site-packages/ctc/rpc/rpc_request/request_utils.py", line 106, in _postprocess_plural_response
    plural_response = _reorder_response_chunks(response_chunks, request)
  File ".../lib/python3.10/site-packages/ctc/rpc/rpc_request/request_utils.py", line 135, in _reorder_response_chunks
    responses_by_id = {
  File ".../lib/python3.10/site-packages/ctc/rpc/rpc_request/request_utils.py", line 136, in <dictcomp>
    response['id']: response
KeyError: 'id'
```

I have a hunch that it's something similar to what was posted on this issue : https://github.com/checkthechain/checkthechain/issues/20

But haven't found a way to solve it.

**Comment by josecyc** [comment]
UPDATE: I just figured out it's because of my rpc

The problem arises when I call 
```
await rpc.async_batch_eth_get_transaction_receipt(transaction_hashes=chunk)
``` 

not sure if it's because sometimes there are blocks that come like this or what:

```
async def parse_block_for_events(active_strategy, block, block_number):
    global snipe_tokens
    global honeypot_pools

    tx_hashes = block["transactions"]
    hex_hashes = [hash.hex() for hash in tx_hashes]
    chunk_size = 100
    max_retries = 10
    retry_delay = 0.1

    chunks = [hex_hashes[i:i+chunk_size] for i in range(0, len(hex_hashes), chunk_size)]
    responses = []

    for chunk_counter, chunk in enumerate(chunks):
        retries = 0
        while retries < max_retries:
            try:
                logger.info(f"Getting transaction receipts for chunk {chunk_counter}...")
                start_time = time.time()

                response = await rpc.async_batch_eth_get_transaction_receipt(transaction_hashes=chunk)
                # logger.debug(f"Raw response for chunk {chunk}: response {response}")

                end_time = time.time()
                logger.info(f"Got transaction receipts for chunk {chunk_counter} in {end_time - start_time} seconds")

                if response:
                    responses.extend(response)
                else:
                    logger.warning(f"No response for chunk {chunk_counter}")

                break  # Exit the retry loop if successful
            except KeyError as e:
                logger.error(f"KeyError in chunk {chunk_counter} attempt {retries}: {e}")
                traceback.print_exc()
                print("chunk", chunk)
                print("all chunks", chunks)
                retries += 1
                if retries < max_retries:
                    await asyncio.sleep(retry_delay * retries)
```

Here it sometimes arbitrarily (and it's something that can last up to half an hour) returns responses_by_id that look like this, clearly an error from my RPC:

```
response_chunks by ID INCCORRECT in CTC [[{'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}}, {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Due to the high consumption or frequency of RPC requests, you have exceeded the rate limit. To increase it, please consider purchasing a more advanced RU package at https://dashboard.blockpi.io'}},
```

And this is how they look when they're correctly converted into `responses_by_id`

```
response_chunks by ID CORRECT in CTC [[{'id': 661904845107460820, 'jsonrpc': '2.0', 'result': {'blockHash': '0xcd93cb137508dd3e3b07d47578bac594d3bfcb982642bdb0cdd7fac84eda09fe', 'blockNumber': '0x1260ce7', 'contractAddress': None, 'cumulativeGasUsed': '0x4002f', 'effectiveGasPrice': '0x1ad636439e', 'from': '0x71cc0e32b2abd066558deba0e47bee9bd8f5ada7', 'gasUsed': '0x4002f', 'logs': [{'address': '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'blockHash': '0xcd93cb137508dd3e3b07d47578bac594d3bfcb982642bdb0cdd7fac84eda09fe', 'blockNumber': '0x1260ce7', 'data': '0x000000000000000000000000000000000000000000000000005b5e8c71fdf330', 'logIndex': '0x0', 'removed': False, 'topics': ['0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c', '0x0000000000000000000000003328f7f4a1d1c57c35df56bbf0c9dcafca309c49'], 'transactionHash': '0xfc0d3ddfdd105bf607c000bd94e53d7cdfdef143eeca647fdf5d0154a0409fd3', 'transactionIndex': '0x0'}, {'address': '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'blockHash': '0xcd93cb137508dd3e3b07d47578bac594d3bfcb982642bdb0cdd7fac84eda09fe', 'blockNumber': '0x1260ce7', 'data': '0x000000000000000000000000000000000000000000000000005b5e8c71fdf330', 'logIndex': '0x1', 'removed': False, 'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x0000000000000000000000003328f7f4a1d1c57c35df56bbf0c9dcafca309c49', '0x0000000000000000000000001d3e23803884f1fdee1042beec88007c6794787b'], 'transactionHash': '0xfc0d3ddfdd105bf607c000bd94e53d7cdfdef143eeca647fdf5d0154a0409fd3', 'transactionIndex': '0x0'}, {'address': '0x46d7c8389b88d9d0331966aec9206462e4ba51ab', 'blockHash': '0xcd93cb137508dd3e3b07d47578bac594d3bfcb982642bdb0cdd7fac84eda09fe', 'blockNumber': '0x1260ce7', 'data': '0x000000000000000000000000000000000000000000000000264d7d607c13fff7', 'logIndex': '0x2', 'removed': False, 'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x0000000000000000000000001d3e23803884f1fdee1042beec88007c6794787b', '0x00000000000000000000000046d7c8389b88d9d0331966aec9206462e4ba51ab'], 'transactionHash': '0xfc0d3ddfdd105bf607c000bd94e53d7cdfdef143eeca647fdf5d0154a0409fd3', 'transactionIndex': '0x0'}, {'address': '0x46d7c8389b88d9d0331966aec9206462e4ba51ab', 'blockHash': '0xcd93cb137508dd3e3b07d47578bac594d3bfcb982642bdb0cdd7fac84eda09fe', 'blockNumber': '0x1260ce7', 'data': '0x0000000000000000000000000000000000000000000000009935f581f04fffde', 'logIndex': '0x3', 'removed': False, 'topics': ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x0000000000000000000000001d3e23803884f1fdee1042beec88007c6794787b', '0x00000000000000000000000071cc0e32b2abd066558deba0e47bee9bd8f5ada7'], 'transactionHash': '0xfc0d3ddfdd105bf607c000bd94e53d7cdfdef143eeca647fdf5d0154a0409fd3', 'transactionIndex': '0x0'}, ....
```

It arbitrarily fixes itself at some point. I guess I just have to measure the rate at which I'm calling my rpc
