### ISSUE TITLE
Running `ctc QUERY` (without additional args) gives error

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/checkthechain#8]
OS: WSL/Ubuntu 20.04
Python 3.8.10

Expected behavior: probably should give an example subcommand or show help for this command?

Actual behavior:

```
(base) caleb@CORUSCANT:~/fei-protocol-core$ ctc QUERY
Traceback (most recent call last):
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/__main__.py", line 4, in <module>
    ctc.cli.run_cli()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/cli/cli_run.py", line 163, in run_cli
    toolcli.run_cli(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 55, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 74, in execute_parsed_command
    execute_command_spec(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 110, in execute_command_spec
    function(**args)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/cli/commands/root_command.py", line 58, in root_command
    metadata = directory.get_erc20_metadata(symbol=item)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/directory/erc20s.py", line 53, in get_erc20_metadata
    erc20_data = load_filesystem_erc20_data(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 135, in new_f
    return execute_with_cache(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 210, in execute_with_cache
    output = old_f(*args, **kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/directory/erc20s.py", line 158, in load_filesystem_erc20_data
    return store_utils.load_file_data(path)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 135, in new_f
    return execute_with_cache(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 210, in execute_with_cache
    output = old_f(*args, **kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/store_utils/store_crud.py", line 34, in load_file_data
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/caleb/.ctcdata/mainnet/erc20s/1inch.csv'
```

**Comment by ditchfieldcaleb** [comment]
also, running `ctc QUERY -h` doesn't give the subcommand help either - just gives the general help

**Comment by sslivkoff** [comment]
`QUERY` is syntax for a block number, address, tx hash, or token symbol

added clarifying message in a33a173e
