### ISSUE TITLE
Error: Exception 'TableDoesNotExist: SELECT name FROM sqlite_schema WHERE type =='table'' thrown when running `ctc setup`

### ISSUE THREAD

**Issue by ByteYue** [fei-protocol/checkthechain#82]
Hi. I'm trying to run ctc on one Linux GCE instance with Python version 3.8.10.
```
xxx@test02:~$ uname -a
Linux test02 5.15.0-1070-gcp #78~20.04.1-Ubuntu SMP Wed Oct 9 22:05:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

When i ran `ctc setup --debug` in my bash i got the following error
```
xxx@test02:~$ ctc setup
[WARNING] ctc config file does not exist; use `ctc setup` on command line to generate a config file
# Setting up ctc...

Running setup process for ctc 0.3.9

Each step is optional
- by default, setup process will leave existing settings unchanged
- setup can be rerun multiple times idempotently

Can skip options by pressing enter at each prompt


## Network Setup


Most ctc operations require an RPC provider

Would you like to specify an RPC provider? (default = yes)

What is the RPC provider URL? localhost:8546

added prefix to url: http://localhost:8546
Provider using: chain_id = 1337
What is the network's name? (enter a blank line to go back)
>
Network block explorer?
What should this node be called? (default = localhost__1337)
Would you like to specify additional RPC providers? (default = no)

Have metadata for the following networks:

      │              name  │       chain_id
──────┼────────────────────┼─────────────────
   1  │          ethereum  │              1
   2  │           ropsten  │              3
   3  │           rinkeby  │              4
   4  │            goerli  │              5
   5  │          optimism  │             10
   6  │             kovan  │             42
   7  │               bnb  │             56
   8  │    optimism_kovan  │             69
   9  │       bnb_testnet  │             97
  10  │            gnosis  │            100
  11  │              heco  │            128
  12  │           polygon  │            137
  13  │            fantom  │            250
  14  │   optimism_goerli  │            420
  15  │             metis  │          1,088
  16  │          moonbeam  │          1,284
  17  │         moonriver  │          1,285
  18  │                    │          1,337
  19  │    fantom_testnet  │          4,002
  20  │            klaytn  │          8,217
  21  │          arbitrum  │         42,161
  22  │    avalanche_fuji  │         43,113
  23  │         avalanche  │         43,114
  24  │    polygon_mumbai  │         80,001
  25  │  arbitrum_rinkeby  │        421,611
  26  │           harmony  │  1,666,600,000
  27  │   harmony_testnet  │  1,666,700,000

Would you like to add metadata for additional networks? (default = no)

Using 27 networks in config

Which network to use as default?
    1.  (chain_id = 1337) (default)
    2. arbitrum (chain_id = 42161)
    3. arbitrum_rinkeby (chain_id = 421611)
    4. avalanche (chain_id = 43114)
    5. avalanche_fuji (chain_id = 43113)
    6. bnb (chain_id = 56)
    7. bnb_testnet (chain_id = 97)
    8. ethereum (chain_id = 1)
    9. fantom (chain_id = 250)
    10. fantom_testnet (chain_id = 4002)
    11. gnosis (chain_id = 100)
    12. goerli (chain_id = 5)
    13. harmony (chain_id = 1666600000)
    14. harmony_testnet (chain_id = 1666700000)
    15. heco (chain_id = 128)
    16. klaytn (chain_id = 8217)
    17. kovan (chain_id = 42)
    18. metis (chain_id = 1088)
    19. moonbeam (chain_id = 1284)
    20. moonriver (chain_id = 1285)
    21. optimism (chain_id = 10)
    22. optimism_goerli (chain_id = 420)
    23. optimism_kovan (chain_id = 69)
    24. polygon (chain_id = 137)
    25. polygon_mumbai (chain_id = 80001)
    26. rinkeby (chain_id = 4)
    27. ropsten (chain_id = 3)
(default =  (chain_id = 1337))

(default =  (chain_id = 1337))
>

Network setup complete


## Data Root Directory

Continue using data directory /home/xxx/ctc_data? (default = yes)

Do you want to disable ctc logging? (default = no)


## CLI Customization

Current color theme:
- title: bold #ce93f9
- metavar: #8be9fd
- description: #b9f29f
- content: #f1fa8c
- option: #64aaaa
- comment: #6272a4

Modify this theme? (default = no)



## Database Setup

ctc stores its collected chain data in an sql database

Current database config:
- dbms: sqlite
- path: /home/xxx/ctc_data/dbs/ctc.db

Continue using this database configuration? (default = yes)

sqlite database already exists

ARGS ('no such table: sqlite_schema',)
[ENTERING DEBUGGER]
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/toolsql/drivers/driver_classes/dbapi_driver.py", line 33, in _select
    cursor = cursor.execute(sql)
sqlite3.OperationalError: no such table: sqlite_schema

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 56, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/xxx/.local/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 86, in execute_parsed_command
    execute_command_spec(
  File "/home/xxx/.local/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 132, in execute_command_spec
    asyncio.run(coroutine)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xxx/.local/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 145, in _async_execute_in_context_manager
    await function(**args)
  File "/home/xxx/.local/lib/python3.8/site-packages/ctc/cli/commands/admin/setup_command.py", line 96, in async_setup_command
    await setup_utils.async_setup_ctc(
  File "/home/xxx/.local/lib/python3.8/site-packages/ctc/config/setup_utils/main_setup.py", line 88, in async_setup_ctc
    db_data = db_setup.setup_dbs(
  File "/home/xxx/.local/lib/python3.8/site-packages/ctc/config/setup_utils/stages/db_setup.py", line 91, in setup_dbs
    _delete_incomplete_chainlink_schemas(db_configs['main'])
  File "/home/xxx/.local/lib/python3.8/site-packages/ctc/config/setup_utils/stages/db_setup.py", line 209, in _delete_incomplete_chainlink_schemas
    table_names = toolsql.get_table_names(conn)
  File "/home/xxx/.local/lib/python3.8/site-packages/toolsql/executors/ddl_executors/metadata_executors.py", line 117, in get_table_names
    return db.get_table_names(conn=conn, permission=permission)
  File "/home/xxx/.local/lib/python3.8/site-packages/toolsql/dbs/db_classes/sqlite_db.py", line 30, in get_table_names
    result = executors.raw_select(
  File "/home/xxx/.local/lib/python3.8/site-packages/toolsql/executors/dml_executors/select_executors.py", line 439, in raw_select
    return driver._select(
  File "/home/xxx/.local/lib/python3.8/site-packages/toolsql/drivers/driver_classes/dbapi_driver.py", line 35, in
_select
    raise spec.convert_exception(e, sql)
toolsql.spec.exceptions.TableDoesNotExist: SELECT name FROM sqlite_schema WHERE type =='table'
```

Then i tried to see the version of my Sqlite3 embedded within python3 and it turned out as follows.
```
xxx@test01:~$ python3
Python 3.8.10 (default, Sep 11 2024, 16:02:53)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.version
'2.6.0'
>>> sqlite3.sqlite_version
'3.31.1'
```

After searching on Goolge i found out [that](https://sqlite.org/forum/forumpost/d90adfbb0a) the table name `sqlite_schema` was introduced after version 3.33.0.
> The name has been changed to "sqlite_schema" as of version 3.33.0.

**Comment by ByteYue** [comment]
I finally succeed to solve this problem, you can refer to https://github.com/checkthechain/checkthechain/issues/78#issuecomment-2464990396 if you're interested in it.
