### ISSUE TITLE
`ctc fei pcv` not working

### ISSUE THREAD

**Issue by ditchfieldcaleb** [fei-protocol/checkthechain#9]
OS: WSL/Ubuntu 20.04
Python 3.8.10

Fresh install, using Alchemy as the provider, on mainnet. 

Error:

```
(base) caleb@CORUSCANT:~/fei-protocol-core$ ctc fei pcv
fetching abi from etherscan: 0xff6f59333cfd8f4ebc14ad0a0e181a83e655d257
saving contract_abi to: /home/caleb/.ctcdata/mainnet/contract_abis/contract__0xff6f59333cfd8f4ebc14ad0a0e181a83e655d257/contract__0xff6f59333cfd8f4ebc14ad0a0e181a83e655d257.json
Traceback (most recent call last):
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/caleb/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/__main__.py", line 4, in <module>
    ctc.cli.run_cli()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/cli/cli_run.py", line 163, in run_cli
    toolcli.run_cli(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 55, in run_cli
    execute_parsed_command(parse_spec=parse_spec, args=args)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 74, in execute_parsed_command
    execute_command_spec(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcli/command_utils/execution.py", line 122, in execute_command_spec
    asyncio.run(function(**args))
  File "/home/caleb/miniconda3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/caleb/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/protocols/fei_utils/cli/fei/pcv_command.py", line 30, in async_pcv_command
    FEI = directory.get_erc20_address('FEI')
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/directory/erc20s.py", line 86, in get_erc20_address
    metadata = get_erc20_metadata(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/directory/erc20s.py", line 53, in get_erc20_metadata
    erc20_data = load_filesystem_erc20_data(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 135, in new_f
    return execute_with_cache(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 210, in execute_with_cache
    output = old_f(*args, **kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/directory/erc20s.py", line 158, in load_filesystem_erc20_data
    return store_utils.load_file_data(path)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 135, in new_f
    return execute_with_cache(
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/toolcache/cache_decorator.py", line 210, in execute_with_cache
    output = old_f(*args, **kwargs)
  File "/home/caleb/miniconda3/lib/python3.8/site-packages/ctc/toolbox/store_utils/store_crud.py", line 34, in load_file_data
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/caleb/.ctcdata/mainnet/erc20s/1inch.csv'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6770febee0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f6770fd2f40>, 18023.4357274)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f6770febcd0>
```

**Comment by sslivkoff** [comment]
fixed in e0e59e91
